### PR TITLE
OFFAPPS-366 Fix unintended reload of APIs

### PR DESCRIPTION
**Pull request by princemaple**
:koala:

This PR eliminates the duplicated API calls made when switching ticket tabs.

/cc @zendesk/quokka

### Reference
- [JIRA OFFAPPS-366](https://zendesk.atlassian.net/browse/OFFAPPS-366)

### Risks
- N/A

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by benhass** [comment]
:+1:

**Comment by princemaple** [comment]
Hello Ben :)

**Comment by adammw** [comment]
@princemaple I think the guys in support were using this functionality as they might have a tab open for a while, and when the come back they want it refreshed as the counts may have changed.

**Comment by princemaple** [comment]
@adammw well too bad it's causing trouble... If it's really a wanted feature, we can create another `.activated` listener that dedicates to the behavior that support relies on.

**Comment by princemaple** [comment]
https://zendesk.atlassian.net/browse/OFFAPPS-400

**Pull request merged**
