### PR TITLE
[OFFAPPS-662]fix date format inconsistency across different browsers

### PR DESCRIPTION
**Pull request by fbvilela**
:bear:

/cc @zendesk/wombat  
      @zendesk/vegemite 

### Description
This PR fixes the inconsistency when displaying a date field across different browsers. 

### References
* JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-662
* Zendesk Ticket: https://support.zendesk.com/agent/tickets/1437825

### Risks
* [ low ] - Displays a date field incorrectly.

### CODE REVIEW

**Comment by tobico** [comment]
:+1:

**Comment by xuebingli** [comment]
:+1:

**Comment by sandlerr** [comment]
:+1:

**Comment by adammw** [comment]
Yay for moment! :+1:

**Pull request merged**
