### PR TITLE
OFFAPPS-362 Display dates in UTC

### PR DESCRIPTION
**Pull request by princemaple**
:koala:

Lotus seems to display dates in UTC, so user data app should do so as well.

/cc @zendesk/quokka

### Reference
- [JIRA OFFAPPS-362](https://zendesk.atlassian.net/browse/OFFAPPS-362)

### Risks
- N/A

### CODE REVIEW

**Comment by atroche** [comment]
:+1:

**Comment by princemaple** [comment]
@maximeprades this won't break anything, would it?

**Comment by maximeprades** [comment]
it shouldn't no. famous last words...

**Comment by danielbreves** [comment]
:+1:

**Pull request merged**
